default:
  before_script:
    # Install JFrog CLI
    - curl -fL https://install-cli.jfrog.io | sh
    # Configure Artifactory instance with JFrog CLI
    - jf config add --url=$JFROG_PLATFORM_URL --access-token=$JFROG_PAT
    - jf config show
stages:
  - build:maven
  - build:docker
build:maven:
  stage: build:maven
  image: maven:latest
  script:
    # Config Maven
    - jf mvn-config
    # Run compile
    - jf mvn clean test-compile -Dcheckstyle.skip -DskipTests
    # Run Maven package
    - jf mvn package spring-boot:repackage -DskipTests -Dcheckstyle.skip
  artifacts:
    paths:
      - target/*.jar
    expire_in: 20 minutes
build:docker:
  stage: build:docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    # Install JFrog CLI
    - curl -fL https://install-cli.jfrog.io | sh
    # Configure Artifactory instance with JFrog CLI
    - jf config add --url=$JFROG_PLATFORM_URL --access-token=$JFROG_PAT
    - jf config show
  script:
    # Build Docker image
    - docker build . --file Dockerfile --build-arg='JAR_FILE=target/*.jar' --tag $ARTIFACTORY_DOCKER_REGISTRY/$DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_VERSION
    # Push Docker image to Artifactory
    - jf rt docker-push $ARTIFACTORY_DOCKER_REGISTRY/$DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_VERSION $DOCKER_REPOSITORY --build-name=$CI_PROJECT_NAME --build-number=$CI_JOB_ID --url $JFROG_PLATFORM_URL --access-token $JFROG_PAT
    #- jf docker push $ARTIFACTORY_DOCKER_REGISTRY/$DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_VERSION --build-name=$CI_PROJECT_NAME --build-number=$CI_JOB_ID
    # Collect the environment variables
    - jf rt bce $CI_PROJECT_NAME $CI_JOB_ID --url $JFROG_PLATFORM_URL --access-token $JFROG_PAT
    # Pass the build information to Artifactory
    - jf rt bp $CI_PROJECT_NAME $CI_JOB_ID --url $JFROG_PLATFORM_URL --access-token $JFROG_PAT
    # Scan published build with fail by default (true)
    - jf bs $CI_PROJECT_NAME $CI_JOB_ID --url $JFROG_PLATFORM_URL --access-token $JFROG_PAT
