resources:
  - name: MyGitHub
    type: GitRepo
    configuration:
      gitProvider: GitHub
      path: cmoyamoradas/my-petclinic
      branches:
        include: main
pipelines:
  - name: my_petclinic_pipeline
    steps:
    - name: step_1
      type: Bash
      configuration:
        inputResources:
          - name: MyGitHub     # Trigger execution on code commit
            trigger: true
      execution:
        onExecute:
          - echo "Hola troncos!"
