name: "JFrog CLI Example"
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Compile code
        run: mvn clean test-compile -Dcheckstyle.skip -DskipTests
      - name: Package
        run: mvn package spring-boot:repackage -DskipTests -Dcheckstyle.skip
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      - name: Run JFrog CLI
        run: |
          # Set the JFrog configuration to use by providing the server ID (configured by the 'jf c add' command).
          #jf c use soleng
          # Ping local-1 Artifactory server
          jf rt ping
          # Collect environment variables for the build
          jf rt bce
          # Collect VCS details from git and add them to the build
          jf rt bag
          # Publish build info
          jf rt bp
