name: "JFrog CLI Example"
on: push
env:
  DOCKER_REPOSITORY: 'carlos-docker-virtual'
  IMAGE_NAME: 'my-pet-clinic'
  IMAGE_VERSION: 'latest'
  ARTIFACTORY_DOCKER_REGISTRY: 'soleng.jfrog.io/carlos-docker-virtual'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Compile code
        run: mvn clean test-compile -Dcheckstyle.skip -DskipTests
      - name: Package
        run: mvn package spring-boot:repackage -DskipTests -Dcheckstyle.skip
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION}}
          build-args: 'JAR_FILE=target/*.jar'
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      - name: Run JFrog CLI
        run: |
          # Set the JFrog configuration to use by providing the server ID (configured by the 'jf c add' command).
          #jf c use soleng
          # Ping local-1 Artifactory server
          jf rt ping
          # Push image to Artifactory
          jf rt docker-push ${{ env.ARTIFACTORY_DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ${{ env.DOCKER_REPOSITORY }} --build-name=${{ github.workflow }} --build-number=${{ github.run_number	}}
          # Collect environment variables for the build
          jf rt bce ${{ github.workflow }} ${{ github.run_number }}
          # Publish build info
          jf rt bp ${{ github.workflow }} ${{ github.run_number }}
